name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Install tools
      run: make install-ci

    - name: Run unit tests
      run: make test-ci

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test_report.xml

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1.5.0
      with:
        file: cover.out
        fail_ci_if_error: true
        verbose: true
